---
title: "Introduction to Reproducibility in R"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Learning Outcomes 



# Introduction

Underlying all biological discoveries are data! The ability to generate reliable measures of biological phenomena through experimental design, modelling or simulation, and then analyse and communicate the results are essential skills for a biologist. This is has always been true but an explosion of large-scale, complex and noisy data has made the acquisition of data skills even more crucial. Such skills include being able to statistically analyse and visualise data generated by research from the ecological to the biomolecular. To critically evaluate inferences arising from these analyses and  advancing the methodology is dependent on research findings being published with their data and analysis code. This is a characteristic known as “reproducibility” and it requires at least some coding. Coding makes everything you do with your raw data explicitly described, totally transparent and completely reproducible. However, learning to code can be a daunting prospect for many biologists!


# Philosophy and approach

Impossible to cover everything to you might ever need!

Different people will use different methods and tools.

Chosen topics are: foundational, widely applicable (in this module and beyond), transferable conceptually:

# Schedule


## 1000 Introduction  
  
  * principles of reproducibility  
  * organisation of data  
  * documentation and dissemination  
  * why R,bioconductor  

## 1030 Parallel Sessions  
  
  * For those without experience in R  
     * Introduction to R  
     * project based approach  
     * stuff from rbs slides  
  * For those with experience in R  
     * advanced data import  
     * advanced data tidying  

## 1115 Coffee in the Atrium  

## 1135 Parallel Sessions  
  
  * For those without experience in R  
     * stuff from rbs slides 
  * For those with experience in R  
     * publication ready figures  

## 1230 Lunch in the Atrium  

## 1315 R Markdown for Reproducible Reports  
  
  * basics  
  * ...  

## 1445 Coffee in the Atrium  

## 1505 more advanced markdown  
  
  * citations, journal templates  
  

data analysis: linear modelling, model selection, multiple testing, github
travel grants