---
title: "Survey Results"
subtitle: "White Rose BBSRC DTP Training: An Introduction to Reproducible Analyses in R."
author: "Emma Rand"
institute: "University of York, UK"
output:
  xaringan::moon_reader:
    css: [default, ../css_files/emma.css, ../css_files/emma-fonts.css]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE,	
                      warning = FALSE,
                      fig.retina = 3)
options(htmltools.dir.version = FALSE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(googlesheets4)
library(showtext)
library(patchwork)
```


```{r fonts, include=FALSE}
font_add_google("Gochi Hand", "Gochi Hand")
showtext_auto()
```




```{r echo=FALSE}
# gs4_auth() run interactively
file <- "https://docs.google.com/spreadsheets/d/11Xx7FLNiure8jF-ti3DNKCj53j3eC8hgMYXA3crvT3I/edit#gid=184416414"
survey <- read_sheet(file) %>% 
  filter(Timestamp > "2022-12-31")

```

# Survey results 1/4 (n = `r dim(survey)[1]`)

```{r echo=FALSE, fig.width = 12, fig.height=5}
r_exp <- survey %>%
  ggplot(aes(x = `Please rate your expertise in R`)) +
  geom_bar(fill = "#9d5e78") +
  scale_x_continuous(name = "Rating",
                     expand = c(0, 0),
                     breaks = 1:10,
                     limits = c(0, 11)) +
  scale_y_continuous(name = "Number of people",
                     expand = c(0, 0),
                     breaks = c(0, 5, 10, 15, 20),
                     limits = c(0, 21)) +
  ggtitle("Expertise in R") +
  theme_classic() +
  theme(plot.background = element_rect(fill = "#f6fafd"),
        panel.background = element_rect(fill = "#f6fafd"),
        plot.title = element_text(size = 50),
        axis.title = element_text(size = 35),
        axis.text.x = element_text(size = 35),
        axis.text.y = element_text(size = 35))

lang_exp <- survey %>%
  ggplot(aes(x = `Please rate your expertise in the non-R language you consider yourself most competent.`)) +
  geom_bar(fill = "#9d5e78") +
  scale_x_continuous(name = "Rating",
                     expand = c(0, 0),
                     breaks = 1:10,
                     limits = c(0, 11)) +
  scale_y_continuous(name = "Number of people",
                     expand = c(0, 0),
                     breaks = c(0, 5, 10, 15, 20),
                     limits = c(0, 21)) +
  ggtitle("Expertise in non-R language") +
  theme_classic() +
  theme(plot.background = element_rect(fill = "#f6fafd"),
        panel.background = element_rect(fill = "#f6fafd"),
        plot.title = element_text(size = 50),
        axis.title = element_text(size = 35),
        axis.text.x = element_text(size = 35),
        axis.text.y = element_text(size = 35))

r_exp + lang_exp &
  plot_annotation(theme = theme(plot.background = element_rect(fill = "#f6fafd")))


```


---
# Survey results 2/4 (n = `r dim(survey)[1]`)



```{r echo=FALSE, fig.width = 12, fig.height=6}
df <- survey %>% group_by(`Have you experience in any of the following programming languages. Tick all that apply.`) %>%  
  summarise(count = n())
df %>%
  ggplot(aes(x = reorder(`Have you experience in any of the following programming languages. Tick all that apply.`, count), y = count)) +
  geom_bar(fill = "#9d5e78", stat = "identity") +
  scale_x_discrete(name = "") +
  scale_y_continuous(name = "Number of people",
                     expand = c(0, 0),
                     breaks = c(0, 5, 10, 15, 20),
                     limits = c(0, 21)) +
  ggtitle("Experience of other langauges") +
  theme_classic() +
  theme(plot.background = element_rect(fill = "#f6fafd"),
        panel.background = element_rect(fill = "#f6fafd"),
        plot.title = element_text(size = 50),
        axis.title = element_text(size = 35),
        axis.text.x = element_text(size = 35),
        axis.text.y = element_text(size = 35)) +
  coord_flip()




```

---
# Survey results 3/4 (n = `r dim(survey)[1]`)

## Current

```{r echo=FALSE, fig.width = 13, fig.height=5}
df <- survey %>% group_by(`In what package/programme are you MOST likely to carry out data analysis and visualisation currently?`) %>%  
  summarise(count = n())
data_pkg <- df %>%
  ggplot(aes(x = reorder(`In what package/programme are you MOST likely to carry out data analysis and visualisation currently?`, count), y = count)) +
  geom_bar(fill = "#9d5e78", stat = "identity") +
  scale_x_discrete(name = "") +
  scale_y_continuous(name = "Number of people",
                     expand = c(0, 0),
                     breaks = c(0, 5, 10, 15, 20),
                     limits = c(0, 24)) +
  ggtitle("Data Analysis package") +
  theme_classic() +
  theme(plot.background = element_rect(fill = "#f6fafd"),
        panel.background = element_rect(fill = "#f6fafd"),
        plot.title = element_text(size = 40),
        axis.title = element_text(size = 35),
        axis.text.x = element_text(size = 35),
        axis.text.y = element_text(size = 35)) +
  coord_flip()


df <- survey %>% group_by(`In what package/programme are you MOST likely to write up analysis results to submit to a journal or similar?`) %>%  
  summarise(count = n())
writing_pkg <- df %>%
  ggplot(aes(x = reorder(`In what package/programme are you MOST likely to write up analysis results to submit to a journal or similar?`, count), y = count)) +
  geom_bar(fill = "#9d5e78", stat = "identity") +
  scale_x_discrete(name = "") +
  scale_y_continuous(name = "Number of people",
                     expand = c(0, 0),
                     breaks = c(0, 5, 10, 15, 20),
                     limits = c(0, 24)) +
  ggtitle("Writing package") +
  theme_classic() +
  theme(plot.background = element_rect(fill = "#f6fafd"),
        panel.background = element_rect(fill = "#f6fafd"),
        plot.title = element_text(size = 40),
        axis.title = element_text(size = 35),
        axis.text.x = element_text(size = 35),
        axis.text.y = element_text(size = 35)) +
  coord_flip()

data_pkg + writing_pkg &
  plot_annotation(theme = theme(plot.background = element_rect(fill = "#f6fafd")))
```



---
# Survey results 4/4 (n = `r dim(survey)[1]`)
Please rate your level of comfort with...

```{r echo=FALSE, fig.width = 12, fig.height=7}
topics <- survey %>%
   select(starts_with("Please rate your level of comfort with the following in R")) %>%
   data.frame(.,check.names = FALSE)
names(topics) <- names(topics) %>%
  sub(pattern = "Please rate your level of comfort with the following in R \\[*",
      replacement = "") %>%
  sub(pattern = "\\]", replacement = "")
my_levels <- c("Not at all comfortable",
               "A bit uncomfortable",
               "Quite comfortable",
               "Completely comfortable")
topics1 <- topics %>% 
#   select(1:8) %>% 
   pivot_longer(names_to = "Topic",
                values_to = "Rating",
                cols = everything())
topics1$Rating <- factor(topics1$Rating, levels = my_levels)
topics1 %>% 
   ggplot(aes(x = Rating)) +
   geom_bar(fill = "#9d5e78") +
   scale_x_discrete(name = "") +
   scale_y_continuous(name = "Number of people",
                      expand = c(0, 0),
                      breaks = c(0, 5, 10, 15, 20, 25),
                      limits = c(0, 30)) +
    facet_wrap(.~ Topic, nrow = 4,  strip.position = "top",
              labeller = label_wrap_gen(width = 35)) + 
   coord_flip() +
   theme_classic() +
   theme(axis.title = element_text(size = 20),
         axis.text.x = element_text(size = 20),
         axis.text.y = element_text(size = 20),
         strip.text.x = element_text(size = 20, lineheight = 0.4,
                                     margin = margin(b = 0)),
         strip.background = element_rect(fill = "#f6fafd", colour = "#f6fafd"),
         plot.background = element_rect(fill = "#f6fafd"),
         panel.background = element_rect(fill = "#f6fafd"))
```





